openapi: 3.0.4
info:
  title: Post Notification API - Subset
  description: API for posting meeting notifications by providing meetingId and meetingTime.
  version: 1.0.0
servers:
  - url: https://app-push-notif-prod-b3vufhiqicj7a.azurewebsites.net
paths:
  /api/Meeting/simple:
    post:
      x-openai-isConsequential: false
      summary: Send meeting details to the notification service
      operationId: postMeetingDetails
      requestBody:
        content:
          application/json:
            schema:
              required:
                - userEmail
                - meetings
              type: object
              properties:
                userEmail:
                  type: string
                  description: The email address of the user
                  format: email
                meetings:
                  type: array
                  description: List of meetings to process.
                  items:
                    type: object
                    required:
                      - meetingId
                      - meetingStartTime
                      - meetingEndTime
                      - attendees
                    properties:
                      meetingId:
                        type: string
                        description: The unique identifier of the meeting.
                      meetingStartTime:
                        type: string
                        description: The start time of the meeting in ISO 8601 format.
                        format: date-time
                      meetingEndTime:
                        type: string
                        description: The end time of the meeting in ISO 8601 format.
                        format: date-time
                      attendees:
                        type: array
                        description: List of meeting attendees.
                        minItems: 1
                        maxItems: 5
                        items:
                          type: string
                          description: Email address of the attendee.
                          format: email
        required: true
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userEmail:
                    type: string
                  appInstancesNotified:
                    type: array
                    items:
                      type: string
                  totalAppInstances:
                    type: integer
                  message:
                    type: string
        '400':
          description: Bad request - user not registered or invalid data

  /api/NoneResponse/SendRSVP:
    post:
      x-openai-isConsequential: false
      summary: Send RSVP reminder for a meeting
      operationId: sendRSVPReminder
      requestBody:
        content:
          application/json:
            schema:
              required:
                - userEmail
                - meetings
              type: object
              properties:
                userEmail:
                  type: string
                  description: The email address of the user
                  format: email
                meetings:
                  type: object
                  description: Meeting details for RSVP reminder.
                  required:
                    - meetingId
                    - meetingStartTime
                  properties:
                    meetingId:
                      type: string
                      description: The unique identifier of the meeting.
                    meetingStartTime:
                      type: string
                      description: The start time of the meeting in ISO 8601 format.
                      format: date-time
        required: true
      responses:
        '200':
          description: RSVP reminder sent successfully
          content:
            text/plain:
              schema:
                type: string
                example: "RSVP reminder sent immediately to user@example.com for meeting meeting123 with Electron support."
        '500':
          description: Internal server error

  /api/ImportantPeople:
    post:
      x-openai-isConsequential: false
      summary: Set important people list
      operationId: setImportantPeople
      requestBody:
        content:
          application/json:
            schema:
              required:
                - ImportantPeople
              type: object
              properties:
                ImportantPeople:
                  type: array
                  description: List of important people (1-5 people).
                  minItems: 1
                  maxItems: 5
                  items:
                    type: string
                    description: Email address or name of the important person.
        required: true
      responses:
        '200':
          description: Important people list updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ImportantPeopleCount:
                    type: integer
                  ImportantPeople:
                    type: array
                    items:
                      type: string
                  Message:
                    type: string
        '400':
          description: Bad request - invalid count (must be 1-5 people)

components: {}